/*
 * Author --> Enoch Oppong D19126484 
 * This is my CRUD Tabbed Pane page
 */
package oppong.enoch_assignment2;

import java.awt.EventQueue;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.beans.Beans;
import java.io.File;
import java.io.FileInputStream;
import java.io.InputStream;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.persistence.RollbackException;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.Timer;
import java.util.regex.*;


/**
 *
 * 
 */
public final class SwirlNTwirl extends JPanel {
    
    public SwirlNTwirl() {
        initComponents();
        showDate();
        showTime();
        if (!Beans.isDesignTime()) {
            entityManager.getTransaction().begin();
        }
    }
void showDate() {
        Date d = new Date();
        SimpleDateFormat s = new SimpleDateFormat("dd-MM-yyyy");
        Date1.setText(s.format(d));

    }
void showTime() {
        new Timer(0, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
               Date d = new Date();
        SimpleDateFormat s = new SimpleDateFormat("hh:mm:ss a");
        Time.setText(s.format(d));
            }
                
            }
        
        ).start();    
    
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        entityManager = java.beans.Beans.isDesignTime() ? null : javax.persistence.Persistence.createEntityManagerFactory("TREATSPU").createEntityManager();
        query = java.beans.Beans.isDesignTime() ? null : entityManager.createQuery("SELECT t FROM Treats t");
        list = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : org.jdesktop.observablecollections.ObservableCollections.observableList(query.getResultList());
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        Date2 = new javax.swing.JLabel();
        Date1 = new javax.swing.JLabel();
        Time2 = new javax.swing.JLabel();
        Time = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        Licecream = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabelClose = new javax.swing.JLabel();
        jLabelMini = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel14 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        caloriesLabel = new javax.swing.JLabel();
        saveButton = new javax.swing.JButton();
        ratingLabel = new javax.swing.JLabel();
        refreshButton = new javax.swing.JButton();
        idField = new javax.swing.JTextField();
        newButton = new javax.swing.JButton();
        makeField = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        flavourField = new javax.swing.JTextField();
        purchasedField = new javax.swing.JTextField();
        colorField = new javax.swing.JTextField();
        containsNutsField = new javax.swing.JTextField();
        veganFriendlyField = new javax.swing.JTextField();
        masterScrollPane = new javax.swing.JScrollPane();
        masterTable = new javax.swing.JTable();
        idLabel = new javax.swing.JLabel();
        makeLabel = new javax.swing.JLabel();
        flavourLabel = new javax.swing.JLabel();
        purchasedLabel = new javax.swing.JLabel();
        colorLabel = new javax.swing.JLabel();
        containsNutsLabel = new javax.swing.JLabel();
        caloriesField = new javax.swing.JTextField();
        veganFriendlyLabel = new javax.swing.JLabel();
        jPanel16 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanel17 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel15 = new javax.swing.JPanel();
        jSlider1 = new javax.swing.JSlider();
        jPanel3 = new javax.swing.JPanel();
        jPanel21 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jPanel22 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jPanel24 = new javax.swing.JPanel();
        jPanel52 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        nutLabel = new javax.swing.JLabel();
        calLabel = new javax.swing.JLabel();
        bjlabel = new javax.swing.JLabel();
        ascreen = new javax.swing.JLabel();
        tscreen = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jPanel25 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jPanel29 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jPanel30 = new javax.swing.JPanel();
        jPanel39 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        name1 = new javax.swing.JTextField();
        email1 = new javax.swing.JTextField();
        number1 = new javax.swing.JTextField();
        jPanel54 = new javax.swing.JPanel();
        jLabel25 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        commentArea = new javax.swing.JTextArea();
        validiation = new javax.swing.JLabel();
        clearBtn1 = new javax.swing.JButton();
        submitBtn1 = new javax.swing.JButton();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        cconfirm = new javax.swing.JLabel();

        FormListener formListener = new FormListener();

        jPanel1.setLayout(null);

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/logo - Copy.jpg"))); // NOI18N
        jPanel1.add(jLabel13);
        jLabel13.setBounds(350, 250, 200, 150);

        Date2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        Date2.setForeground(new java.awt.Color(102, 0, 102));
        Date2.setText("Date:");
        jPanel1.add(Date2);
        Date2.setBounds(610, 560, 58, 20);

        Date1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        Date1.setText("Date:");
        jPanel1.add(Date1);
        Date1.setBounds(670, 560, 230, 20);

        Time2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        Time2.setForeground(new java.awt.Color(102, 0, 102));
        Time2.setText("Time:");
        jPanel1.add(Time2);
        Time2.setBounds(610, 590, 60, 20);

        Time.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        Time.setText("Time:");
        jPanel1.add(Time);
        Time.setBounds(670, 590, 230, 20);

        jLabel2.setFont(new java.awt.Font("Ravie", 0, 36)); // NOI18N
        jLabel2.setText("Ice-Cream Database");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(220, 130, 490, 40);

        jLabel1.setFont(new java.awt.Font("Ravie", 0, 36)); // NOI18N
        jLabel1.setText("Welcome To Swirl N Twirl");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(140, 70, 640, 60);

        Licecream.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/ice cream banner.jpg"))); // NOI18N
        jPanel1.add(Licecream);
        Licecream.setBounds(0, 40, 930, 640);

        jPanel5.setBackground(new java.awt.Color(255, 118, 117));

        jLabelClose.setFont(new java.awt.Font("Segoe Script", 1, 24)); // NOI18N
        jLabelClose.setForeground(new java.awt.Color(255, 255, 255));
        jLabelClose.setText("    X");
        jLabelClose.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelClose.addMouseListener(formListener);

        jLabelMini.setFont(new java.awt.Font("Segoe Script", 1, 24)); // NOI18N
        jLabelMini.setText("      -");
        jLabelMini.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelMini.addMouseListener(formListener);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGap(0, 598, Short.MAX_VALUE)
                .addComponent(jLabelMini)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelClose, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelClose, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelMini, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel1.add(jPanel5);
        jPanel5.setBounds(180, 0, 750, 30);

        jPanel6.setBackground(new java.awt.Color(255, 234, 167));

        jLabel3.setFont(new java.awt.Font("Segoe Script", 1, 24)); // NOI18N
        jLabel3.setText("Welcome Page");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 27, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel1.add(jPanel6);
        jPanel6.setBounds(0, 0, 180, 30);

        jPanel14.setBackground(new java.awt.Color(235, 47, 6));

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 930, Short.MAX_VALUE)
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel14);
        jPanel14.setBounds(0, 30, 930, 10);

        jTabbedPane1.addTab("Welcome Page", jPanel1);

        jPanel2.setBackground(new java.awt.Color(255, 204, 204));

        caloriesLabel.setFont(new java.awt.Font("Segoe Script", 1, 18)); // NOI18N
        caloriesLabel.setText("Calories:");

        saveButton.setBackground(new java.awt.Color(255, 250, 101));
        saveButton.setFont(new java.awt.Font("Segoe Script", 1, 18)); // NOI18N
        saveButton.setText("Save");
        saveButton.addActionListener(formListener);

        ratingLabel.setFont(new java.awt.Font("Segoe Script", 1, 18)); // NOI18N
        ratingLabel.setText("Rating:");

        refreshButton.setBackground(new java.awt.Color(255, 175, 64));
        refreshButton.setFont(new java.awt.Font("Segoe Script", 1, 18)); // NOI18N
        refreshButton.setText("Refresh");
        refreshButton.addActionListener(formListener);

        idField.setBackground(new java.awt.Color(85, 239, 196));
        idField.setFont(new java.awt.Font("Segoe Script", 1, 18)); // NOI18N

        org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, masterTable, org.jdesktop.beansbinding.ELProperty.create("${selectedElement.id}"), idField, org.jdesktop.beansbinding.BeanProperty.create("text"));
        binding.setSourceUnreadableValue("null");
        bindingGroup.addBinding(binding);
        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ, masterTable, org.jdesktop.beansbinding.ELProperty.create("${selectedElement != null}"), idField, org.jdesktop.beansbinding.BeanProperty.create("enabled"));
        bindingGroup.addBinding(binding);

        newButton.setBackground(new java.awt.Color(205, 132, 241));
        newButton.setFont(new java.awt.Font("Segoe Script", 1, 18)); // NOI18N
        newButton.setText("New");
        newButton.addActionListener(formListener);

        makeField.setBackground(new java.awt.Color(85, 239, 196));
        makeField.setFont(new java.awt.Font("Segoe Script", 1, 18)); // NOI18N

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, masterTable, org.jdesktop.beansbinding.ELProperty.create("${selectedElement.make}"), makeField, org.jdesktop.beansbinding.BeanProperty.create("text"));
        binding.setSourceUnreadableValue("null");
        bindingGroup.addBinding(binding);
        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ, masterTable, org.jdesktop.beansbinding.ELProperty.create("${selectedElement != null}"), makeField, org.jdesktop.beansbinding.BeanProperty.create("enabled"));
        bindingGroup.addBinding(binding);

        jButton1.setBackground(new java.awt.Color(255, 77, 77));
        jButton1.setFont(new java.awt.Font("Segoe Script", 1, 18)); // NOI18N
        jButton1.setText("Delete");
        jButton1.addActionListener(formListener);

        flavourField.setBackground(new java.awt.Color(85, 239, 196));
        flavourField.setFont(new java.awt.Font("Segoe Script", 1, 18)); // NOI18N

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, masterTable, org.jdesktop.beansbinding.ELProperty.create("${selectedElement.flavour}"), flavourField, org.jdesktop.beansbinding.BeanProperty.create("text"));
        binding.setSourceUnreadableValue("null");
        bindingGroup.addBinding(binding);
        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ, masterTable, org.jdesktop.beansbinding.ELProperty.create("${selectedElement != null}"), flavourField, org.jdesktop.beansbinding.BeanProperty.create("enabled"));
        bindingGroup.addBinding(binding);

        purchasedField.setBackground(new java.awt.Color(85, 239, 196));
        purchasedField.setFont(new java.awt.Font("Segoe Script", 1, 18)); // NOI18N

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, masterTable, org.jdesktop.beansbinding.ELProperty.create("${selectedElement.purchased}"), purchasedField, org.jdesktop.beansbinding.BeanProperty.create("text"));
        binding.setSourceUnreadableValue("null");
        bindingGroup.addBinding(binding);
        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ, masterTable, org.jdesktop.beansbinding.ELProperty.create("${selectedElement != null}"), purchasedField, org.jdesktop.beansbinding.BeanProperty.create("enabled"));
        bindingGroup.addBinding(binding);

        colorField.setBackground(new java.awt.Color(85, 239, 196));
        colorField.setFont(new java.awt.Font("Segoe Script", 1, 18)); // NOI18N

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, masterTable, org.jdesktop.beansbinding.ELProperty.create("${selectedElement.color}"), colorField, org.jdesktop.beansbinding.BeanProperty.create("text"));
        binding.setSourceUnreadableValue("null");
        bindingGroup.addBinding(binding);
        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ, masterTable, org.jdesktop.beansbinding.ELProperty.create("${selectedElement != null}"), colorField, org.jdesktop.beansbinding.BeanProperty.create("enabled"));
        bindingGroup.addBinding(binding);

        containsNutsField.setBackground(new java.awt.Color(85, 239, 196));
        containsNutsField.setFont(new java.awt.Font("Segoe Script", 1, 18)); // NOI18N

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, masterTable, org.jdesktop.beansbinding.ELProperty.create("${selectedElement.containsNuts}"), containsNutsField, org.jdesktop.beansbinding.BeanProperty.create("text"));
        binding.setSourceUnreadableValue("null");
        bindingGroup.addBinding(binding);
        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ, masterTable, org.jdesktop.beansbinding.ELProperty.create("${selectedElement != null}"), containsNutsField, org.jdesktop.beansbinding.BeanProperty.create("enabled"));
        bindingGroup.addBinding(binding);

        veganFriendlyField.setBackground(new java.awt.Color(85, 239, 196));
        veganFriendlyField.setFont(new java.awt.Font("Segoe Script", 1, 18)); // NOI18N

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, masterTable, org.jdesktop.beansbinding.ELProperty.create("${selectedElement.veganFriendly}"), veganFriendlyField, org.jdesktop.beansbinding.BeanProperty.create("text"));
        binding.setSourceUnreadableValue("null");
        bindingGroup.addBinding(binding);
        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ, masterTable, org.jdesktop.beansbinding.ELProperty.create("${selectedElement != null}"), veganFriendlyField, org.jdesktop.beansbinding.BeanProperty.create("enabled"));
        bindingGroup.addBinding(binding);

        masterTable.setBackground(new java.awt.Color(153, 128, 250));
        masterTable.setFont(new java.awt.Font("Segoe Script", 1, 18)); // NOI18N

        org.jdesktop.swingbinding.JTableBinding jTableBinding = org.jdesktop.swingbinding.SwingBindings.createJTableBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, list, masterTable);
        org.jdesktop.swingbinding.JTableBinding.ColumnBinding columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${id}"));
        columnBinding.setColumnName("Id");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${make}"));
        columnBinding.setColumnName("Make");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${flavour}"));
        columnBinding.setColumnName("Flavour");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${purchased}"));
        columnBinding.setColumnName("Purchased");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${color}"));
        columnBinding.setColumnName("Color");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${containsNuts}"));
        columnBinding.setColumnName("Contains Nuts");
        columnBinding.setColumnClass(Integer.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${veganFriendly}"));
        columnBinding.setColumnName("Vegan Friendly");
        columnBinding.setColumnClass(Integer.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${calories}"));
        columnBinding.setColumnName("Calories");
        columnBinding.setColumnClass(Integer.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${rating}"));
        columnBinding.setColumnName("Rating");
        columnBinding.setColumnClass(Integer.class);
        bindingGroup.addBinding(jTableBinding);

        masterScrollPane.setViewportView(masterTable);

        idLabel.setFont(new java.awt.Font("Segoe Script", 1, 18)); // NOI18N
        idLabel.setText("Id:");

        makeLabel.setFont(new java.awt.Font("Segoe Script", 1, 18)); // NOI18N
        makeLabel.setText("Make:");

        flavourLabel.setFont(new java.awt.Font("Segoe Script", 1, 18)); // NOI18N
        flavourLabel.setText("Flavour:");

        purchasedLabel.setFont(new java.awt.Font("Segoe Script", 1, 18)); // NOI18N
        purchasedLabel.setText("Purchased:");

        colorLabel.setFont(new java.awt.Font("Segoe Script", 1, 18)); // NOI18N
        colorLabel.setText("Color:");

        containsNutsLabel.setFont(new java.awt.Font("Segoe Script", 1, 18)); // NOI18N
        containsNutsLabel.setText("Contains Nuts:");

        caloriesField.setBackground(new java.awt.Color(85, 239, 196));
        caloriesField.setFont(new java.awt.Font("Segoe Script", 1, 18)); // NOI18N

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, masterTable, org.jdesktop.beansbinding.ELProperty.create("${selectedElement.calories}"), caloriesField, org.jdesktop.beansbinding.BeanProperty.create("text"));
        binding.setSourceUnreadableValue("null");
        bindingGroup.addBinding(binding);
        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ, masterTable, org.jdesktop.beansbinding.ELProperty.create("${selectedElement != null}"), caloriesField, org.jdesktop.beansbinding.BeanProperty.create("enabled"));
        bindingGroup.addBinding(binding);

        veganFriendlyLabel.setFont(new java.awt.Font("Segoe Script", 1, 18)); // NOI18N
        veganFriendlyLabel.setText("Vegan Friendly:");

        jPanel16.setBackground(new java.awt.Color(255, 234, 167));

        jLabel4.setFont(new java.awt.Font("Segoe Script", 1, 24)); // NOI18N
        jLabel4.setText("C.R.U.D");

        javax.swing.GroupLayout jPanel16Layout = new javax.swing.GroupLayout(jPanel16);
        jPanel16.setLayout(jPanel16Layout);
        jPanel16Layout.setHorizontalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel16Layout.setVerticalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );

        jPanel17.setBackground(new java.awt.Color(250, 211, 144));

        jLabel5.setFont(new java.awt.Font("Segoe Script", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("   X");
        jLabel5.addMouseListener(formListener);

        jLabel6.setFont(new java.awt.Font("Segoe Script", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("    -");
        jLabel6.addMouseListener(formListener);

        javax.swing.GroupLayout jPanel17Layout = new javax.swing.GroupLayout(jPanel17);
        jPanel17.setLayout(jPanel17Layout);
        jPanel17Layout.setHorizontalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel17Layout.createSequentialGroup()
                .addGap(0, 717, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel17Layout.setVerticalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel15.setBackground(new java.awt.Color(237, 76, 103));

        javax.swing.GroupLayout jPanel15Layout = new javax.swing.GroupLayout(jPanel15);
        jPanel15.setLayout(jPanel15Layout);
        jPanel15Layout.setHorizontalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel15Layout.setVerticalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 23, Short.MAX_VALUE)
        );

        jSlider1.setBackground(new java.awt.Color(0, 206, 201));
        jSlider1.setFont(new java.awt.Font("Segoe Script", 1, 13)); // NOI18N
        jSlider1.setMajorTickSpacing(1);
        jSlider1.setMaximum(10);
        jSlider1.setMinimum(1);
        jSlider1.setPaintLabels(true);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, masterTable, org.jdesktop.beansbinding.ELProperty.create("${selectedElement.rating}"), jSlider1, org.jdesktop.beansbinding.BeanProperty.create("value"));
        binding.setSourceNullValue(jSlider1.getMinimum());
        bindingGroup.addBinding(binding);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addComponent(jPanel17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(masterScrollPane)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(idLabel)
                            .addComponent(makeLabel)
                            .addComponent(flavourLabel)
                            .addComponent(purchasedLabel)
                            .addComponent(colorLabel)
                            .addComponent(containsNutsLabel)
                            .addComponent(veganFriendlyLabel)
                            .addComponent(caloriesLabel)
                            .addComponent(ratingLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(caloriesField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 206, Short.MAX_VALUE)
                            .addComponent(veganFriendlyField, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(containsNutsField, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(colorField, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(purchasedField, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(flavourField, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(makeField, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(idField, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSlider1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(newButton, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(refreshButton, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(saveButton)
                        .addContainerGap())))
            .addComponent(jPanel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(masterScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(idLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(idField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(makeLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(makeField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(flavourLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(flavourField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(purchasedLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(purchasedField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(colorLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(colorField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(containsNutsLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(containsNutsField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(veganFriendlyLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(veganFriendlyField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(caloriesLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(caloriesField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ratingLabel)
                    .addComponent(jSlider1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(newButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(refreshButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(saveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addComponent(jPanel15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jTabbedPane1.addTab("C.R.U.D", jPanel2);

        jPanel3.setBackground(new java.awt.Color(223, 249, 251));
        jPanel3.setLayout(null);

        jPanel21.setBackground(new java.awt.Color(27, 20, 100));

        jLabel7.setFont(new java.awt.Font("Segoe Script", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Statistics");

        javax.swing.GroupLayout jPanel21Layout = new javax.swing.GroupLayout(jPanel21);
        jPanel21.setLayout(jPanel21Layout);
        jPanel21Layout.setHorizontalGroup(
            jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel21Layout.setVerticalGroup(
            jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel21Layout.createSequentialGroup()
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addGap(7, 7, 7))
        );

        jPanel3.add(jPanel21);
        jPanel21.setBounds(0, 0, 113, 34);

        jPanel22.setBackground(new java.awt.Color(87, 88, 187));

        jLabel11.setFont(new java.awt.Font("Segoe Script", 1, 24)); // NOI18N
        jLabel11.setText(" X");
        jLabel11.addMouseListener(formListener);

        jLabel12.setFont(new java.awt.Font("Segoe Script", 1, 24)); // NOI18N
        jLabel12.setText("   -");
        jLabel12.addMouseListener(formListener);

        javax.swing.GroupLayout jPanel22Layout = new javax.swing.GroupLayout(jPanel22);
        jPanel22.setLayout(jPanel22Layout);
        jPanel22Layout.setHorizontalGroup(
            jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel22Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel12)
                .addGap(18, 18, 18)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel22Layout.setVerticalGroup(
            jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel3.add(jPanel22);
        jPanel22.setBounds(120, 0, 811, 34);

        jPanel24.setBackground(new java.awt.Color(217, 128, 250));

        javax.swing.GroupLayout jPanel24Layout = new javax.swing.GroupLayout(jPanel24);
        jPanel24.setLayout(jPanel24Layout);
        jPanel24Layout.setHorizontalGroup(
            jPanel24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 930, Short.MAX_VALUE)
        );
        jPanel24Layout.setVerticalGroup(
            jPanel24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel3.add(jPanel24);
        jPanel24.setBounds(0, 34, 930, 10);

        jPanel52.setBackground(new java.awt.Color(253, 167, 223));

        javax.swing.GroupLayout jPanel52Layout = new javax.swing.GroupLayout(jPanel52);
        jPanel52.setLayout(jPanel52Layout);
        jPanel52Layout.setHorizontalGroup(
            jPanel52Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel52Layout.setVerticalGroup(
            jPanel52Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel3.add(jPanel52);
        jPanel52.setBounds(1, 660, 930, 18);

        jButton2.setBackground(new java.awt.Color(142, 68, 173));
        jButton2.setFont(new java.awt.Font("Segoe Script", 1, 24)); // NOI18N
        jButton2.setText("Submit");
        jButton2.addMouseListener(formListener);
        jPanel3.add(jButton2);
        jButton2.setBounds(639, 510, 130, 30);

        nutLabel.setBackground(new java.awt.Color(255, 255, 255));
        nutLabel.setFont(new java.awt.Font("Segoe Script", 1, 24)); // NOI18N
        nutLabel.setText("????");
        jPanel3.add(nutLabel);
        nutLabel.setBounds(690, 430, 160, 30);

        calLabel.setFont(new java.awt.Font("Segoe Script", 1, 24)); // NOI18N
        calLabel.setText("????");
        jPanel3.add(calLabel);
        calLabel.setBounds(640, 380, 150, 30);

        bjlabel.setFont(new java.awt.Font("Segoe Script", 1, 24)); // NOI18N
        bjlabel.setText("????");
        jPanel3.add(bjlabel);
        bjlabel.setBounds(640, 320, 150, 30);

        ascreen.setFont(new java.awt.Font("Segoe Script", 1, 24)); // NOI18N
        ascreen.setText("????");
        jPanel3.add(ascreen);
        ascreen.setBounds(550, 260, 190, 30);

        tscreen.setFont(new java.awt.Font("Segoe Script", 1, 24)); // NOI18N
        tscreen.setText("????");
        jPanel3.add(tscreen);
        tscreen.setBounds(570, 210, 220, 30);

        jLabel19.setFont(new java.awt.Font("Segoe Script", 1, 24)); // NOI18N
        jLabel19.setText("How many Ice-Cream flavours are red?");
        jPanel3.add(jLabel19);
        jLabel19.setBounds(160, 430, 520, 30);

        jLabel18.setBackground(new java.awt.Color(255, 255, 255));
        jLabel18.setFont(new java.awt.Font("Segoe Script", 1, 24)); // NOI18N
        jLabel18.setText("What is the average calorie count?");
        jPanel3.add(jLabel18);
        jLabel18.setBounds(160, 380, 450, 30);

        jLabel17.setFont(new java.awt.Font("Segoe Script", 1, 24)); // NOI18N
        jLabel17.setText("How many Ben & Jerrys are there?");
        jPanel3.add(jLabel17);
        jLabel17.setBounds(160, 320, 480, 30);

        jLabel16.setFont(new java.awt.Font("Segoe Script", 1, 24)); // NOI18N
        jLabel16.setText("What is the average rating?");
        jPanel3.add(jLabel16);
        jLabel16.setBounds(160, 260, 370, 30);

        jLabel15.setFont(new java.awt.Font("Segoe Script", 1, 24)); // NOI18N
        jLabel15.setText("How many Ice-Cream records?");
        jPanel3.add(jLabel15);
        jLabel15.setBounds(160, 200, 400, 40);

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagesUsed/image2.png"))); // NOI18N
        jLabel14.setOpaque(true);
        jPanel3.add(jLabel14);
        jLabel14.setBounds(0, 60, 930, 600);

        jTabbedPane1.addTab("Statistics", jPanel3);

        jPanel4.setBackground(new java.awt.Color(186, 220, 88));
        jPanel4.setLayout(null);

        jPanel25.setBackground(new java.awt.Color(46, 213, 115));

        jLabel8.setFont(new java.awt.Font("Segoe Script", 1, 24)); // NOI18N
        jLabel8.setText("Help Page");

        javax.swing.GroupLayout jPanel25Layout = new javax.swing.GroupLayout(jPanel25);
        jPanel25.setLayout(jPanel25Layout);
        jPanel25Layout.setHorizontalGroup(
            jPanel25Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel25Layout.setVerticalGroup(
            jPanel25Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );

        jPanel4.add(jPanel25);
        jPanel25.setBounds(0, 0, 130, 29);

        jPanel29.setBackground(new java.awt.Color(85, 239, 196));

        jLabel9.setFont(new java.awt.Font("Segoe Script", 1, 24)); // NOI18N
        jLabel9.setText(" X");
        jLabel9.addMouseListener(formListener);

        jLabel10.setFont(new java.awt.Font("Segoe Script", 1, 24)); // NOI18N
        jLabel10.setText(" -");
        jLabel10.addMouseListener(formListener);

        javax.swing.GroupLayout jPanel29Layout = new javax.swing.GroupLayout(jPanel29);
        jPanel29.setLayout(jPanel29Layout);
        jPanel29Layout.setHorizontalGroup(
            jPanel29Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel29Layout.createSequentialGroup()
                .addGap(0, 712, Short.MAX_VALUE)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel29Layout.setVerticalGroup(
            jPanel29Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel29Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel4.add(jPanel29);
        jPanel29.setBounds(137, 0, 794, 29);

        jPanel30.setBackground(new java.awt.Color(253, 203, 110));

        javax.swing.GroupLayout jPanel30Layout = new javax.swing.GroupLayout(jPanel30);
        jPanel30.setLayout(jPanel30Layout);
        jPanel30Layout.setHorizontalGroup(
            jPanel30Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 930, Short.MAX_VALUE)
        );
        jPanel30Layout.setVerticalGroup(
            jPanel30Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 17, Short.MAX_VALUE)
        );

        jPanel4.add(jPanel30);
        jPanel30.setBounds(0, 36, 930, 17);

        jPanel39.setBackground(new java.awt.Color(0, 184, 148));

        javax.swing.GroupLayout jPanel39Layout = new javax.swing.GroupLayout(jPanel39);
        jPanel39.setLayout(jPanel39Layout);
        jPanel39Layout.setHorizontalGroup(
            jPanel39Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 930, Short.MAX_VALUE)
        );
        jPanel39Layout.setVerticalGroup(
            jPanel39Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 19, Short.MAX_VALUE)
        );

        jPanel4.add(jPanel39);
        jPanel39.setBounds(0, 668, 930, 19);

        jLabel20.setFont(new java.awt.Font("Segoe Script", 1, 20)); // NOI18N
        jLabel20.setText("Welcome to the Swirl N Twirl Help Center");
        jPanel4.add(jLabel20);
        jLabel20.setBounds(200, 60, 470, 33);

        jLabel21.setFont(new java.awt.Font("Segoe Script", 1, 20)); // NOI18N
        jLabel21.setText("Questions? Need Help? Please fill out a form below: ");
        jPanel4.add(jLabel21);
        jLabel21.setBounds(10, 100, 570, 33);

        jLabel22.setFont(new java.awt.Font("Segoe Script", 1, 20)); // NOI18N
        jLabel22.setText("Name:");
        jPanel4.add(jLabel22);
        jLabel22.setBounds(30, 150, 70, 20);

        jLabel23.setFont(new java.awt.Font("Segoe Script", 1, 20)); // NOI18N
        jLabel23.setText("Email:");
        jPanel4.add(jLabel23);
        jLabel23.setBounds(30, 200, 80, 20);

        jLabel24.setFont(new java.awt.Font("Segoe Script", 1, 20)); // NOI18N
        jLabel24.setText("Number:");
        jPanel4.add(jLabel24);
        jLabel24.setBounds(30, 250, 100, 20);

        name1.setFont(new java.awt.Font("Segoe Script", 1, 20)); // NOI18N
        jPanel4.add(name1);
        name1.setBounds(100, 140, 320, 40);

        email1.setFont(new java.awt.Font("Segoe Script", 1, 20)); // NOI18N
        email1.addActionListener(formListener);
        jPanel4.add(email1);
        email1.setBounds(110, 190, 290, 40);

        number1.setFont(new java.awt.Font("Segoe Script", 1, 20)); // NOI18N
        jPanel4.add(number1);
        number1.setBounds(130, 240, 250, 40);

        jPanel54.setBackground(new java.awt.Color(246, 229, 141));

        javax.swing.GroupLayout jPanel54Layout = new javax.swing.GroupLayout(jPanel54);
        jPanel54.setLayout(jPanel54Layout);
        jPanel54Layout.setHorizontalGroup(
            jPanel54Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 930, Short.MAX_VALUE)
        );
        jPanel54Layout.setVerticalGroup(
            jPanel54Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        jPanel4.add(jPanel54);
        jPanel54.setBounds(0, 290, 930, 10);

        jLabel25.setFont(new java.awt.Font("Segoe Script", 1, 20)); // NOI18N
        jLabel25.setText("Comments:");
        jPanel4.add(jLabel25);
        jLabel25.setBounds(0, 300, 120, 20);

        commentArea.setColumns(20);
        commentArea.setFont(new java.awt.Font("Segoe Script", 1, 18)); // NOI18N
        commentArea.setRows(5);
        jScrollPane1.setViewportView(commentArea);

        jPanel4.add(jScrollPane1);
        jScrollPane1.setBounds(0, 320, 470, 290);

        validiation.setFont(new java.awt.Font("Segoe Script", 1, 18)); // NOI18N
        jPanel4.add(validiation);
        validiation.setBounds(0, 630, 650, 30);

        clearBtn1.setBackground(new java.awt.Color(246, 229, 141));
        clearBtn1.setFont(new java.awt.Font("Segoe Script", 1, 20)); // NOI18N
        clearBtn1.setText("Clear");
        clearBtn1.addActionListener(formListener);
        jPanel4.add(clearBtn1);
        clearBtn1.setBounds(700, 630, 91, 30);

        submitBtn1.setBackground(new java.awt.Color(255, 190, 118));
        submitBtn1.setFont(new java.awt.Font("Segoe Script", 1, 20)); // NOI18N
        submitBtn1.setText("Submit");
        submitBtn1.addActionListener(formListener);
        jPanel4.add(submitBtn1);
        submitBtn1.setBounds(810, 630, 120, 30);

        jLabel26.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/loads_1.jpg"))); // NOI18N
        jPanel4.add(jLabel26);
        jLabel26.setBounds(480, 300, 440, 320);

        jLabel27.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/dancing ice.gif"))); // NOI18N
        jPanel4.add(jLabel27);
        jLabel27.setBounds(730, 60, 200, 170);

        jLabel28.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/logo - Copy.jpg"))); // NOI18N
        jPanel4.add(jLabel28);
        jLabel28.setBounds(430, 130, 200, 150);

        cconfirm.setFont(new java.awt.Font("Segoe Script", 1, 20)); // NOI18N
        jPanel4.add(cconfirm);
        cconfirm.setBounds(640, 260, 290, 30);

        jTabbedPane1.addTab("Help Page", jPanel4);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );

        bindingGroup.bind();
    }

    // Code for dispatching events from components to event handlers.

    private class FormListener implements java.awt.event.ActionListener, java.awt.event.MouseListener {
        FormListener() {}
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            if (evt.getSource() == saveButton) {
                SwirlNTwirl.this.saveButtonActionPerformed(evt);
            }
            else if (evt.getSource() == refreshButton) {
                SwirlNTwirl.this.refreshButtonActionPerformed(evt);
            }
            else if (evt.getSource() == newButton) {
                SwirlNTwirl.this.newButtonActionPerformed(evt);
            }
            else if (evt.getSource() == jButton1) {
                SwirlNTwirl.this.jButton1ActionPerformed(evt);
            }
            else if (evt.getSource() == email1) {
                SwirlNTwirl.this.email1ActionPerformed(evt);
            }
            else if (evt.getSource() == clearBtn1) {
                SwirlNTwirl.this.clearBtn1ActionPerformed(evt);
            }
            else if (evt.getSource() == submitBtn1) {
                SwirlNTwirl.this.submitBtn1ActionPerformed(evt);
            }
        }

        public void mouseClicked(java.awt.event.MouseEvent evt) {
            if (evt.getSource() == jLabelClose) {
                SwirlNTwirl.this.jLabelCloseMouseClicked(evt);
            }
            else if (evt.getSource() == jLabelMini) {
                SwirlNTwirl.this.jLabelMiniMouseClicked(evt);
            }
            else if (evt.getSource() == jLabel5) {
                SwirlNTwirl.this.jLabel5MouseClicked(evt);
            }
            else if (evt.getSource() == jLabel6) {
                SwirlNTwirl.this.jLabel6MouseClicked(evt);
            }
            else if (evt.getSource() == jLabel11) {
                SwirlNTwirl.this.jLabel11MouseClicked(evt);
            }
            else if (evt.getSource() == jLabel12) {
                SwirlNTwirl.this.jLabel12MouseClicked(evt);
            }
            else if (evt.getSource() == jButton2) {
                SwirlNTwirl.this.jButton2MouseClicked(evt);
            }
            else if (evt.getSource() == jLabel9) {
                SwirlNTwirl.this.jLabel9MouseClicked(evt);
            }
            else if (evt.getSource() == jLabel10) {
                SwirlNTwirl.this.jLabel10MouseClicked(evt);
            }
        }

        public void mouseEntered(java.awt.event.MouseEvent evt) {
        }

        public void mouseExited(java.awt.event.MouseEvent evt) {
        }

        public void mousePressed(java.awt.event.MouseEvent evt) {
        }

        public void mouseReleased(java.awt.event.MouseEvent evt) {
        }
    }// </editor-fold>//GEN-END:initComponents

    
    @SuppressWarnings("unchecked")
    //Refresh Button
    private void refreshButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshButtonActionPerformed
        entityManager.getTransaction().rollback();
        entityManager.getTransaction().begin();
        java.util.Collection data = query.getResultList();
        for (Object entity : data) {//start for
            entityManager.refresh(entity);
        }//end for
        list.clear();
        list.addAll(data);
    }//GEN-LAST:event_refreshButtonActionPerformed

    //New Entry Button
    private void newButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newButtonActionPerformed
        oppong.enoch_assignment2.Treats t = new oppong.enoch_assignment2.Treats();
        entityManager.persist(t);
        list.add(t);
        int row = list.size() - 1;
        masterTable.setRowSelectionInterval(row, row);
        masterTable.scrollRectToVisible(masterTable.getCellRect(row, 0, true));
    }//GEN-LAST:event_newButtonActionPerformed
    
    //Save Button
    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
        try {//start try
            entityManager.getTransaction().commit();
            entityManager.getTransaction().begin();
        } catch (RollbackException rex) {//start catch
            rex.printStackTrace();
            entityManager.getTransaction().begin();
            List<oppong.enoch_assignment2.Treats> merged = new ArrayList<oppong.enoch_assignment2.Treats>(list.size());
            for (oppong.enoch_assignment2.Treats t : list) {
                merged.add(entityManager.merge(t));
            }
            list.clear();
            list.addAll(merged);
        }//end catch
    }//GEN-LAST:event_saveButtonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int[] selected = masterTable.getSelectedRows();
        List<oppong.enoch_assignment2.Treats> toRemove = new ArrayList<oppong.enoch_assignment2.Treats>(selected.length);
        for (int idx = 0; idx < selected.length; idx++) {
            oppong.enoch_assignment2.Treats t = list.get(masterTable.convertRowIndexToModel(selected[idx]));
            toRemove.add(t);
            entityManager.remove(t);
        }
        list.removeAll(toRemove);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jLabelCloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelCloseMouseClicked
        System.exit(0);
    }//GEN-LAST:event_jLabelCloseMouseClicked

    private void jLabelMiniMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelMiniMouseClicked
        //this.setState(JPanel.ICONIFIED);
    }//GEN-LAST:event_jLabelMiniMouseClicked

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        System.exit(0);
    }//GEN-LAST:event_jLabel5MouseClicked

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        //this.setState(JPanel.ICONIFIED);
    }//GEN-LAST:event_jLabel6MouseClicked

    private void jLabel11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MouseClicked
        System.exit(0);
    }//GEN-LAST:event_jLabel11MouseClicked

    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked
        System.exit(0);
    }//GEN-LAST:event_jLabel9MouseClicked

    private void jLabel12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel12MouseClicked
        //this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_jLabel12MouseClicked

    private void jLabel10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseClicked
        //this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_jLabel10MouseClicked

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
         // Code for refresh button
        // tscreen and refreshbnt
        
        String total = Treats.count();
        tscreen.setText(total);
        
        String average = Treats.average();
        ascreen.setText(average);
        
        String bicej = Treats.bandj();
        bjlabel.setText(bicej);
        
        String calAverage = Treats.calAverage();
        calLabel.setText(calAverage);
        
        String red = Treats.redice();
        nutLabel.setText(red);
    }//GEN-LAST:event_jButton2MouseClicked

    private void email1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_email1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_email1ActionPerformed

    private void clearBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearBtn1ActionPerformed
        name1.setText("  ");
        email1.setText("  ");
        number1.setText("  ");
    }//GEN-LAST:event_clearBtn1ActionPerformed

    private void submitBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitBtn1ActionPerformed
        name1.setText("  ");
        //email1.setText("  ");
        number1.setText("  ");
        commentArea.setText("  ");
        validiation.setText("Please enter your details!");
        
        String email = email1.getText(); //vemail is the text box for the email address
        String regEx = "\\b[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\\.[A-Za-z]{2,4}\\b";

        Pattern p = Pattern.compile(regEx);
        Matcher m = p.matcher(email);

        if(m.find()) 
        {
         cconfirm.setText("Valid Email address!");
        validiation.setText("Thank you for your message. We will get back to you shortly!");}
        else
        {
         cconfirm.setText("Invalid Email address!");
         
    }//GEN-LAST:event_submitBtn1ActionPerformed
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Date1;
    private javax.swing.JLabel Date2;
    private javax.swing.JLabel Licecream;
    private javax.swing.JLabel Time;
    private javax.swing.JLabel Time2;
    private javax.swing.JLabel ascreen;
    private javax.swing.JLabel bjlabel;
    private javax.swing.JLabel calLabel;
    private javax.swing.JTextField caloriesField;
    private javax.swing.JLabel caloriesLabel;
    private javax.swing.JLabel cconfirm;
    private javax.swing.JButton clearBtn1;
    private javax.swing.JTextField colorField;
    private javax.swing.JLabel colorLabel;
    private javax.swing.JTextArea commentArea;
    private javax.swing.JTextField containsNutsField;
    private javax.swing.JLabel containsNutsLabel;
    private javax.swing.JTextField email1;
    private javax.persistence.EntityManager entityManager;
    private javax.swing.JTextField flavourField;
    private javax.swing.JLabel flavourLabel;
    private javax.swing.JTextField idField;
    private javax.swing.JLabel idLabel;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelClose;
    private javax.swing.JLabel jLabelMini;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel21;
    private javax.swing.JPanel jPanel22;
    private javax.swing.JPanel jPanel24;
    private javax.swing.JPanel jPanel25;
    private javax.swing.JPanel jPanel29;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel30;
    private javax.swing.JPanel jPanel39;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel52;
    private javax.swing.JPanel jPanel54;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSlider jSlider1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private java.util.List<oppong.enoch_assignment2.Treats> list;
    private javax.swing.JTextField makeField;
    private javax.swing.JLabel makeLabel;
    private javax.swing.JScrollPane masterScrollPane;
    private javax.swing.JTable masterTable;
    private javax.swing.JTextField name1;
    private javax.swing.JButton newButton;
    private javax.swing.JTextField number1;
    private javax.swing.JLabel nutLabel;
    private javax.swing.JTextField purchasedField;
    private javax.swing.JLabel purchasedLabel;
    private javax.persistence.Query query;
    private javax.swing.JLabel ratingLabel;
    private javax.swing.JButton refreshButton;
    private javax.swing.JButton saveButton;
    private javax.swing.JButton submitBtn1;
    private javax.swing.JLabel tscreen;
    private javax.swing.JLabel validiation;
    private javax.swing.JTextField veganFriendlyField;
    private javax.swing.JLabel veganFriendlyLabel;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
    public static void main(String[] args) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SwirlNTwirl.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SwirlNTwirl.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SwirlNTwirl.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SwirlNTwirl.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        EventQueue.invokeLater(new Runnable() {
            public void run() {
                JFrame frame = new JFrame();
                frame.setContentPane(new SwirlNTwirl());
                frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
                frame.pack();
                frame.setVisible(true);
            }
        });
       
    }

         
            
    void pack() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    void setLocationRelativeTo(Object object) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    void setDefaultCloseOperation(int EXIT_ON_CLOSE) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    private void dispose() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    
    
}
